-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema happiness_MySQL_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema happiness_MySQL_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `happiness_MySQL_database` DEFAULT CHARACTER SET utf8 ;
USE `happiness_MySQL_database` ;

-- -----------------------------------------------------
-- Table `happiness_MySQL_database`.`happiness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happiness_MySQL_database`.`happiness` (
  `country_or_region_id` INT NOT NULL,
  `country_or_region` VARCHAR(45) NULL,
  `happiness_score` DECIMAL(3,2) NULL,
  `happiness_score_category` VARCHAR(45) NULL,
  `peace_index` DECIMAL(3,2) NULL,
  `peace_index_category` VARCHAR(45) NULL,
  `feel_religious` DECIMAL(5,2) NULL,
  `feel_religious_category` VARCHAR(45) NULL,
  PRIMARY KEY (`country_or_region_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `happiness_MySQL_database`.`happiness`
-- -----------------------------------------------------
START TRANSACTION;
USE `happiness_MySQL_database`;
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (1, 'Afghanistan', 3.20, 'sad', 3.57, 'dangerous', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (2, 'Albania', 4.72, 'not_happy', 1.82, 'safe', 39.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (3, 'Algeria', 5.21, 'not_happy', 2.22, 'not_safe', 95.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (4, 'Argentina', 6.09, 'happy', 1.99, 'safe', 65.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (5, 'Armenia', 4.56, 'not_happy', 2.29, 'not_safe', 73.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (6, 'Australia', 7.23, 'very_happy', 1.42, 'very_safe', 32.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (7, 'Austria', 7.25, 'very_happy', 1.29, 'very_safe', 55.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (8, 'Azerbaijan', 5.21, 'not_happy', 2.42, 'dangerous', 50.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (9, 'Bahrain', 6.20, 'very_happy', 2.36, 'dangerous', 94.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (10, 'Bangladesh', 4.46, 'sad', 2.13, 'not_safe', 100.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (11, 'Belarus', 5.32, 'not_happy', 2.12, 'not_safe', 34.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (12, 'Belgium', 6.92, 'very_happy', 1.53, 'very_safe', 33.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (13, 'Benin', 4.88, 'not_happy', 1.99, 'safe', 93.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (14, 'Bhutan', 5.08, 'not_happy', 1.51, 'very_safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (15, 'Bolivia', 5.78, 'happy', 2.04, 'not_safe', 89.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (16, 'Bosnia and Herzegovina', 5.39, 'happy', 2.02, 'not_safe', 77.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (17, 'Botswana', 3.49, 'sad', 1.68, 'very_safe', 77.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (18, 'Brazil', 6.30, 'very_happy', 2.27, 'not_safe', 87.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (19, 'Bulgaria', 5.01, 'not_happy', 1.61, 'very_safe', 34.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (20, 'Burkina Faso', 4.59, 'not_happy', 2.18, 'not_safe', 88.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (21, 'Burundi', 3.78, 'sad', 2.52, 'dangerous', 98.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (22, 'Cambodia', 4.70, 'not_happy', 2.07, 'not_safe', 96.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (23, 'Cameroon', 5.04, 'not_happy', 2.54, 'dangerous', 96.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (24, 'Canada', 7.28, 'very_happy', 1.33, 'very_safe', 42.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (25, 'Central African Republic', 3.08, 'sad', 3.30, 'dangerous', 94.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (26, 'Chad', 4.35, 'sad', 2.52, 'dangerous', 95.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (27, 'Chile', 6.44, 'very_happy', 1.63, 'very_safe', 70.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (28, 'China', 5.19, 'not_happy', 2.22, 'not_safe', 7.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (29, 'Colombia', 6.12, 'happy', 2.66, 'dangerous', 83.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (30, 'Comoros', 3.97, 'sad', 2.08, 'unknown', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (31, 'Congo (Brazzaville)', 4.81, 'not_happy', 2.08, 'unknown', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (32, 'Congo (Kinshasa)', 4.42, 'sad', 2.08, 'unknown', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (33, 'Costa Rica', 7.17, 'very_happy', 1.71, 'very_safe', 79.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (34, 'Croatia', 5.43, 'happy', 1.64, 'very_safe', 70.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (35, 'Cyprus', 6.05, 'happy', 1.91, 'safe', 75.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (36, 'Czech Republic', 6.85, 'very_happy', 1.38, 'very_safe', 21.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (37, 'Denmark', 7.60, 'very_happy', 1.32, 'very_safe', 19.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (38, 'Dominican Republic', 5.42, 'happy', 2.04, 'not_safe', 87.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (39, 'Ecuador', 6.03, 'happy', 1.98, 'safe', 82.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (40, 'Egypt', 4.17, 'sad', 2.52, 'dangerous', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (41, 'El Salvador', 6.25, 'very_happy', 2.26, 'not_safe', 83.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (42, 'Estonia', 5.89, 'happy', 1.73, 'safe', 16.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (43, 'Ethiopia', 4.29, 'sad', 2.43, 'dangerous', 99.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (44, 'Finland', 7.77, 'very_happy', 1.49, 'very_safe', 28.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (45, 'France', 6.59, 'very_happy', 1.89, 'safe', 30.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (46, 'Gabon', 4.80, 'not_happy', 2.11, 'not_safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (47, 'Gambia', 4.52, 'sad', 2.08, 'unknown', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (48, 'Georgia', 4.52, 'sad', 2.12, 'not_safe', 81.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (49, 'Germany', 6.98, 'very_happy', 1.55, 'very_safe', 40.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (50, 'Ghana', 5.00, 'not_happy', 1.80, 'safe', 95.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (51, 'Greece', 5.29, 'not_happy', 1.93, 'safe', 71.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (52, 'Guatemala', 6.44, 'very_happy', 2.26, 'not_safe', 88.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (53, 'Guinea', 4.53, 'sad', 2.12, 'not_safe', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (54, 'Haiti', 3.60, 'sad', 2.05, 'not_safe', 75.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (55, 'Honduras', 5.86, 'happy', 2.34, 'dangerous', 84.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (56, 'Hong Kong', 5.43, 'happy', 2.08, 'unknown', 24.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (57, 'Hungary', 5.76, 'happy', 1.54, 'very_safe', 39.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (58, 'Iceland', 7.49, 'very_happy', 1.07, 'very_safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (59, 'India', 4.01, 'sad', 2.60, 'dangerous', 90.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (60, 'Indonesia', 5.19, 'not_happy', 1.78, 'safe', 99.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (61, 'Iran', 4.55, 'not_happy', 2.54, 'dangerous', 73.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (62, 'Iraq', 4.44, 'sad', 3.37, 'dangerous', 84.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (63, 'Ireland', 7.02, 'very_happy', 1.39, 'very_safe', 54.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (64, 'Israel', 7.14, 'very_happy', 2.74, 'dangerous', 51.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (65, 'Italy', 6.22, 'very_happy', 1.75, 'safe', 72.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (66, 'Ivory Coast', 4.94, 'not_happy', 2.08, 'unknown', 88.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (67, 'Jamaica', 5.89, 'happy', 2.04, 'not_safe', 70.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (68, 'Japan', 5.89, 'happy', 1.37, 'very_safe', 24.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (69, 'Jordan', 4.91, 'not_happy', 2.01, 'safe', 96.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (70, 'Kazakhstan', 5.81, 'happy', 1.93, 'safe', 43.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (71, 'Kenya', 4.51, 'sad', 2.30, 'not_safe', 94.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (72, 'Kosovo', 6.10, 'happy', 2.05, 'not_safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (73, 'Kuwait', 6.02, 'happy', 1.79, 'safe', 91.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (74, 'Kyrgyzstan', 5.26, 'not_happy', 2.08, 'unknown', 72.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (75, 'Laos', 4.80, 'not_happy', 1.80, 'safe', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (76, 'Latvia', 5.94, 'happy', 1.72, 'very_safe', 39.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (77, 'Lebanon', 5.20, 'not_happy', 2.80, 'dangerous', 87.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (78, 'Lesotho', 3.80, 'sad', 2.17, 'not_safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (79, 'Liberia', 3.98, 'sad', 1.89, 'safe', 94.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (80, 'Libya', 5.52, 'happy', 3.28, 'dangerous', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (81, 'Lithuania', 6.15, 'happy', 1.73, 'safe', 42.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (82, 'Luxembourg', 7.09, 'very_happy', 2.08, 'unknown', 39.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (83, 'Madagascar', 3.93, 'sad', 1.87, 'safe', 93.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (84, 'Malawi', 3.41, 'sad', 1.78, 'safe', 99.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (85, 'Malaysia', 5.34, 'not_happy', 1.53, 'very_safe', 96.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (86, 'Mali', 4.39, 'sad', 2.71, 'dangerous', 95.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (87, 'Malta', 6.73, 'very_happy', 2.08, 'unknown', 86.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (88, 'Mauritania', 4.49, 'sad', 2.33, 'not_safe', 98.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (89, 'Mauritius', 5.89, 'happy', 1.56, 'very_safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (90, 'Mexico', 6.60, 'very_happy', 2.60, 'dangerous', 73.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (91, 'Moldova', 5.53, 'happy', 1.95, 'safe', 72.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (92, 'Mongolia', 5.28, 'not_happy', 1.79, 'safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (93, 'Montenegro', 5.52, 'happy', 1.94, 'safe', 71.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (94, 'Morocco', 5.21, 'not_happy', 2.07, 'not_safe', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (95, 'Mozambique', 4.47, 'sad', 2.10, 'not_safe', 86.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (96, 'Myanmar', 4.36, 'sad', 2.39, 'dangerous', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (97, 'Namibia', 4.64, 'not_happy', 1.89, 'safe', 92.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (98, 'Nepal', 4.91, 'not_happy', 2.00, 'safe', 93.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (99, 'Netherlands', 7.49, 'very_happy', 1.53, 'very_safe', 33.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (100, 'New Zealand', 7.31, 'very_happy', 1.22, 'very_safe', 33.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (101, 'Nicaragua', 6.10, 'happy', 2.31, 'not_safe', 84.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (102, 'Niger', 4.63, 'not_happy', 2.39, 'dangerous', 100.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (103, 'Nigeria', 5.26, 'not_happy', 2.90, 'dangerous', 96.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (104, 'North Macedonia', 5.27, 'not_happy', 1.93, 'safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (105, 'Northern Cyprus', 5.72, 'happy', 2.08, 'unknown', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (106, 'Norway', 7.55, 'very_happy', 1.54, 'very_safe', 21.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (107, 'Pakistan', 5.65, 'happy', 3.07, 'dangerous', 92.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (108, 'Palestinian Territories', 4.70, 'not_happy', 2.08, 'unknown', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (109, 'Panama', 6.32, 'very_happy', 1.80, 'safe', 88.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (110, 'Paraguay', 5.74, 'happy', 2.06, 'not_safe', 92.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (111, 'Peru', 5.70, 'happy', 2.02, 'not_safe', 84.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (112, 'Philippines', 5.63, 'happy', 2.52, 'dangerous', 96.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (113, 'Poland', 6.18, 'happy', 1.65, 'very_safe', 75.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (114, 'Portugal', 5.69, 'happy', 1.27, 'very_safe', 72.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (115, 'Qatar', 6.37, 'very_happy', 1.70, 'very_safe', 95.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (116, 'Romania', 6.07, 'happy', 1.61, 'very_safe', 84.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (117, 'Russia', 5.65, 'happy', 3.09, 'dangerous', 34.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (118, 'Rwanda', 3.33, 'sad', 2.01, 'not_safe', 95.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (119, 'Saudi Arabia', 6.38, 'very_happy', 2.41, 'dangerous', 93.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (120, 'Senegal', 4.68, 'not_happy', 1.88, 'safe', 96.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (121, 'Serbia', 5.60, 'happy', 1.81, 'safe', 54.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (122, 'Sierra Leone', 4.37, 'sad', 1.82, 'safe', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (123, 'Singapore', 6.26, 'very_happy', 1.35, 'very_safe', 70.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (124, 'Slovakia', 6.20, 'very_happy', 1.55, 'very_safe', 47.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (125, 'Slovenia', 6.12, 'happy', 1.36, 'very_safe', 47.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (126, 'Somalia', 4.67, 'not_happy', 3.30, 'dangerous', 100.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (127, 'South Africa', 4.72, 'not_happy', 2.40, 'dangerous', 85.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (128, 'South Korea', 5.90, 'happy', 1.87, 'safe', 43.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (129, 'South Sudan', 2.85, 'sad', 3.53, 'dangerous', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (130, 'Spain', 6.35, 'very_happy', 1.70, 'very_safe', 49.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (131, 'Sri Lanka', 4.37, 'sad', 1.99, 'safe', 99.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (132, 'Swaziland', 4.21, 'sad', 2.08, 'unknown', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (133, 'Sweden', 7.34, 'very_happy', 1.53, 'very_safe', 17.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (134, 'Switzerland', 7.48, 'very_happy', 1.38, 'very_safe', 41.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (135, 'Syria', 3.46, 'sad', 3.57, 'dangerous', 89.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (136, 'Taiwan', 6.45, 'very_happy', 1.72, 'very_safe', 45.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (137, 'Tajikistan', 5.47, 'happy', 2.20, 'not_safe', 85.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (138, 'Tanzania', 3.23, 'sad', 1.86, 'safe', 89.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (139, 'Thailand', 6.01, 'happy', 2.28, 'not_safe', 97.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (140, 'Togo', 4.08, 'sad', 2.20, 'not_safe', 80.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (141, 'Trinidad & Tobago', 6.19, 'very_happy', 2.08, 'unknown', 72.00, 'unknown');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (142, 'Tunisia', 4.46, 'sad', 2.04, 'not_safe', 93.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (143, 'Turkey', 5.37, 'not_happy', 3.02, 'dangerous', 82.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (144, 'Turkmenistan', 5.25, 'not_happy', 2.26, 'not_safe', 80.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (145, 'Uganda', 4.19, 'sad', 2.20, 'not_safe', 93.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (146, 'Ukraine', 4.33, 'sad', 2.95, 'dangerous', 46.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (147, 'United Arab Emirates', 6.82, 'very_happy', 1.85, 'safe', 91.00, 'religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (148, 'United Kingdom', 7.05, 'very_happy', 1.80, 'safe', 27.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (149, 'United States', 6.89, 'very_happy', 2.40, 'dangerous', 69.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (150, 'Uruguay', 6.29, 'very_happy', 1.71, 'very_safe', 41.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (151, 'Uzbekistan', 6.17, 'happy', 2.17, 'not_safe', 59.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (152, 'Venezuela', 4.71, 'not_happy', 2.67, 'dangerous', 79.00, 'slightly_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (153, 'Vietnam', 5.18, 'not_happy', 1.88, 'safe', 30.00, 'not_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (154, 'Yemen', 3.38, 'sad', 3.41, 'dangerous', 99.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (155, 'Zambia', 4.11, 'sad', 1.80, 'safe', 95.00, 'very_religious');
INSERT INTO `happiness_MySQL_database`.`happiness` (`country_or_region_id`, `country_or_region`, `happiness_score`, `happiness_score_category`, `peace_index`, `peace_index_category`, `feel_religious`, `feel_religious_category`) VALUES (156, 'Zimbabwe', 3.66, 'sad', 2.46, 'dangerous', 88.00, 'religious');

COMMIT;

